config/routes.rb
Rails.application.routes.draw do

  get '/getting-started', to: 'steps#getting_started'
  get '/front-end-in-rails', to: 'steps#front_end_in_rails'
  get '/html-document-structure', to: 'steps#html_document_structure'
  get '/html-css-js', to: 'steps#html_css_js'
  get '/html5', to: 'steps#html5'
  get '/rails-templates-helper-methods', to: 'steps#rails_templates_helper_methods'
  get '/layouts-and-rendering', to: 'steps#layouts_and_rendering'
  get '/css-definition-examples', to: 'steps#css_definition_examples'
  get '/css-frameworks', to: 'steps#css_frameworks'
  get '/grid-system', to: 'steps#grid_system'
  get '/css3', to: 'steps#css3'
  get '/css-techniques', to: 'steps#css_techniques'
  get '/scss', to: 'steps#scss'
  get '/smacss', to: 'steps#smacss'
  get '/dom-manipulation', to: 'steps#dom_manipulation'
  get '/js-libraries', to: 'steps#js_libraries'
  get '/jquery-tutorial', to: 'steps#jquery_tutorial'
  get '/turbolinks', to: 'steps#turbolinks'
  get '/coffeescript', to: 'steps#coffeescript'
  get '/ajax', to: 'steps#ajax'
  get '/weather-widget', to: 'steps#weather_widget'
  get '/better-alerts', to: 'steps#better_alerts'
  get '/next-steps', to: 'steps#next_steps'

  root to: 'steps#overview'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/steps_controller.rb
class StepsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/steps_helper.rb
module StepsHelper
end

app/views/layouts/_header.html.erb
<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Front-End Development</a>
    </div>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<ul class="nav nav-sidebar">
  <li class="<%= 'active' if current_page?('/') %>">
    <%= link_to 'Overview', root_path %>
  </li>
  <li class="<%= 'active' if current_page?('/getting-started') %>">
    <%= link_to 'Getting Started', getting_started_path %>
  </li>
  <li class="<%= 'active' if current_page?('/html-css-js') %>">
    <%= link_to 'HTML / CSS / JS', html_css_js_path %>
  </li>
  <li class="<%= 'active' if current_page?('/front-end-in-rails') %>">
    <%= link_to 'Front End in Rails', front_end_in_rails_path %>
  </li>
</ul>
<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>HTML</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/html-document-structure') %>">
    <%= link_to 'HTML Document Structure', html_document_structure_path %>
  </li>
  <li class="<%= 'active' if current_page?('/html5') %>">
    <%= link_to 'HTML5', html5_path %>
  </li>
  <li class="<%= 'active' if current_page?('/layouts-and-rendering') %>">
    <%= link_to 'Rails Layouts & Rendering', layouts_and_rendering_path %>
  </li>
  <li class="<%= 'active' if current_page?('/rails-templates-helper-methods') %>">
    <%= link_to 'Rails Templates & Helper methods', rails_templates_helper_methods_path %>
  </li>
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>CSS</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/css-definition-examples') %>">
    <%= link_to 'Definition & Examples', css_definition_examples_path %>
  </li>
  <li class="<%= 'active' if current_page?('/css-frameworks') %>">
    <%= link_to 'CSS Frameworks', css_frameworks_path %>
  </li>
  <li class="<%= 'active' if current_page?('/grid-system') %>">
    <%= link_to 'Grid System', grid_system_path %>
  </li>
  <li class="<%= 'active' if current_page?('/css3') %>">
    <%= link_to 'CSS3', css3_path %>
  </li>
  <li class="<%= 'active' if current_page?('/css-techniques') %>">
    <%= link_to 'CSS Techniques', css_techniques_path %>
  </li>
  <li class="<%= 'active' if current_page?('/scss') %>">
    <%= link_to 'SASS & SCSS', scss_path %>
  </li>
  <li class="<%= 'active' if current_page?('/smacss') %>">
    <%= link_to 'SMACSS', smacss_path %>
  </li>
</ul>

<ul class="nav nav-sidebar">
  <li class='disabled'>
    <a href="#" ><h4>Javascript</h4></a>
  </li>
  <li class="<%= 'active' if current_page?('/dom-manipulation') %>">
    <%= link_to 'DOM Manipulation', dom_manipulation_path %>
  </li>
  <li class="<%= 'active' if current_page?('/js-libraries') %>">
    <%= link_to 'JS Libraries: jQuery', js_libraries_path %>
  </li>
  <li class="<%= 'active' if current_page?('/coffeescript') %>">
    <%= link_to 'Coffeescript', coffeescript_path %>
  </li>
  <li class="<%= 'active' if current_page?('/better-alerts') %>">
    <%= link_to 'Better Alerts', better_alerts_url %>
  </li>
  <li class="<%= 'active' if current_page?('/ajax') %>">
    <%= link_to 'AJAX', ajax_path %>
  </li>
  <li class="<%= 'active' if current_page?('/turbolinks') %>">
    <%= link_to 'Turbolinks', turbolinks_path %>
  </li>
  <li class="<%= 'active' if current_page?('/weather-widget') %>">
    <%= link_to "What's the weather like?", weather_widget_path %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Front-End Development</title>

  <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css">
  <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
  <link rel="stylesheet" type="text/css" href="http://bootswatch.com/flatly/bootstrap.min.css">
  <link rel="stylesheet" href="http://yandex.st/highlightjs/8.0/styles/monokai.min.css">
  <script src="http://yandex.st/highlightjs/8.0/highlight.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container-fluid">
    <div class="row">
      <div class="col-sm-3 col-md-2 sidebar">
        <%= render 'layouts/navigation' %>
      </div>
      <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

app/views/steps/ajax.html.erb
<h1 class="page-header">AJAX</h1>

<blockquote>
  <p>AJAX or Asynchronous JavaScript refers to sending data to, and retrieve data from, a server in the background without interfering with the display and behavior of the existing page.</p>
</blockquote>

<h2>Goals</h2>
<blockquote>
  <ul>
    <li>Give our comment form asynchronous features.</li>
    <li>Respond to different formats</li>
    <li>Use our new Notification class to give feedback</li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Rails <code>form_for</code> takes a <code>remote</code> argument so the form will be submitted by Ajax rather than by the browser's normal submit mechanism.</p>
  <pre><code>remote: true</code></pre>
  <div class="alert alert-info">Notice the <code>data-remote="true"</code> attribute added to the form.</div>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Ajax isn't just client-side, you also need to do some work on the server side to support it.</p>
  <pre><code>if @comment.save
  respond_to do |format|
    @message = 'Comment was successfully posted.'
    format.html { redirect_to @project, notice: @message }
    format.js { @message_type = 'notice' }
  end
else
  respond_to do |format|
    @message = @comment.errors.full_messages.join('. ')
    format.html { redirect_to @project, alert: @message }
    format.js { @message_type = 'alert' }
  end
end</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Display notifications from <code>create.js.erb</code></p>
  <pre><code>new Notification("&lt;%= @message %&gt;", "&lt;%= @message_type %&gt;");</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Add newly created comment to the list</p>
  <pre><code>&lt;% if @comment.valid? %&gt;
  $("&lt;%= escape_javascript(render @comment) %&gt;").prependTo(".comments");
&lt;% end %&gt;
new Notification("&lt;%= @message %&gt;", "&lt;%= @message_type %&gt;");</code></pre>
</blockquote>

<h3>Step 5</h3>
<blockquote>
  <p>Reset the form</p>
  <pre><code>&lt;% if @comment.valid? %&gt;
  $("&lt;%= escape_javascript(render @comment) %&gt;").prependTo(".comments");
  $('#new_comment')[0].reset()
&lt;% end %&gt;
new Notification("&lt;%= @message %&gt;", "&lt;%= @message_type %&gt;");</code></pre>
</blockquote>

<h2>Explanation</h2>
<blockquote>
  <p>So what happened?</p>
  <ul>
    <li><a href="https://github.com/rails/jquery-ujs">jQuery-ujs</a> intercepts the call to submit the form and sends a request to the server asynchronously.</li>
    <li>Rails responds to the call normally until the <code>respond_to</code> block.</li>
    <li>Rails returns a javascript response to the browser instead of the HTML default one.</li>
    <li>Browser executes the javascript response.</li>
  </ul>
</blockquote>

app/views/steps/better_alerts.html.erb
<h1 class="page-header">Better Alerts</h1>
<blockquote>
  <p>Our flash messages are a bit weak at the moment. In this lesson, we will learn how to create a CoffeeScript class to handle the animation of our Flash messages.</p>
</blockquote>
<h2>Goals</h2>
<blockquote>
  <ul>
    <li>Create a CoffeeScript class</li>
    <li>Play with jQuery Animations and Events</li>
  </ul>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Create a flash message template</p>
  <pre><code>&lt;div class="flash-container"&gt;
  &lt;div class="flash-alert"&gt;
    Text can't be blank
  &lt;/div&gt;
&lt;/div&gt;</code></pre>
</blockquote>

<h3>Step 2</h3>
<blockquote>
  <p>Give it some style</p>
  <pre><code>.flash-container {
  display: none;
  cursor: pointer;
  margin: 0;
  text-align: center;
  color: #fff;
  position: fixed;
  bottom: 0;
  width: 100%;
  opacity: 0.8;
  z-index: 100;
  font-size: 1.2em;

  .flash-notice, .flash-alert {
    padding: 12px;
  }

  .flash-notice {
    background: #49C;
    text-shadow: 0 1px 1px #178;
  }
  .flash-alert {
    background: #C67;
    text-shadow: 0 1px 1px #945;
  }
}</code></pre>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <p>Create a partial to handle all flash messages</p>
  <pre><code>&lt;div class="flash-container"&gt;&lt;/div&gt;
&lt;script type="text/javascript"&gt;
  &lt;% flash.each do |name, msg| %&gt;
    new Notification('&lt;%= msg %&gt;', '&lt;%= name %&gt;')
  &lt;% end -%&gt;
&lt;/script&gt;</code></pre>
</blockquote>

<h3>Step 4</h3>
<blockquote>
  <p>Create a Notification CoffeeScript class</p>
  <pre><code>class @Notification
  constructor: (message, type)->
    @message = message
    @type = type
    @flash = $(".flash-container").html("").show()
    @render()

  render: ->
    $('&lt;div/&gt;',
      class: "flash-#{@type}",
      html: @message
    ).appendTo(".flash-container")</code></pre>
</blockquote>

<h3>Step 5</h3>
<blockquote>
  <p>Animate the notification message</p>
  <pre><code>class @Notification
  constructor: (message, type)->
    @message = message
    @type = type
    @flash = $(".flash-container").html("").show()
    @render()
    @bindEvents()

  render: ->
    $('&lt;div/&gt;',
      class: "flash-#{@type}",
      html: @message
    ).appendTo(".flash-container")

  bindEvents: =>
    @flash.click -> $(@).fadeOut()
    setTimeout (=> @flash.fadeOut()), 5000</code></pre>
</blockquote>

app/views/steps/css3.html.erb
<h1 class="page-header">CSS3</h1>
<blockquote>
  <p>CSS3 is the latest standard for CSS.</p>
  <p>CSS3 is completely backwards-compatible with earlier versions of CSS.</p>
  <p>This section teaches you about the new features in CSS3!</p>
</blockquote>

<h3>New properties</h3>
<blockquote>
  <h3><code>border-radius</code></h3>
  <div class="well" style='border-radius:15px;'>
    border-radius:15px;
  </div>
  <h3><code>box-shadow</code></h3>
  <div class="well" style='box-shadow: 0 1px 3px #999;'>
    box-shadow: 0 1px 3px #999;
  </div>
  <h3><code>box-shadow</code></h3>
  <div class="well" style="background-image: linear-gradient(#999, #eee);">
    background-image: linear-gradient(#999, #333);
  </div>
  <h3><code>transition</code></h3>
  <div style="background-color: black; color: white; padding: 15px; transition: width 1s; width: 350px;" onmouseover="$(this).css({width: '400px'});" onmouseout="$(this).css({width: '350px'});">
    transition: width 1s;<br />
    width: 350px;<br />
    &:hover { width: '400px'; }
  </div>
  <h3><code>animation</code></h3>
  <p><a href="http://anthonycalzadilla.com/css3-ATAT/index.html">AT-AT Walker</a></p>
  <h3><code>transform</code></h3>
  <a href="http://mrdoob.github.io/three.js/examples/css3d_periodictable.html">CSS3 Periodic table</a>
</blockquote>

app/views/steps/css_definition_examples.html.erb
<h1 class='page-header'>What is CSS?</h1>

<h2>Definition</h2>
<blockquote>
  <p>
    CSS stands for <strong>C</strong>ascading <strong>S</strong>tyle<strong>s</strong>heets. It's a language for creating <strong>rules</strong> that can <strong>select</strong> various elements on the page and change their <strong>visual properties</strong>.
  </p>

  <ul>
    <li>
      <strong>C</strong>ascading - The 'cascade' is one of the trickier elements of CSS to master, but it basically means you can define a bunch of styling rules of different strengths, and CSS will apply them all, resolving any conflicting rules by allowing stronger rules overwrite (or <em>cascade</em> over) weaker rules.
    </li>
    <li>
      <strong>S</strong>tyle<strong>s</strong>heets - CSS files are called 'stylesheets' because they allow you to put your
      styling rules into a separate document (a 'sheet') of file type .css, and then choose to
      include one or more in a given HTML page. This is a <em>very</em> important feature for sites with many pages,
      because it allows you to write your rules once and then include them everywhere on your site with
      a single link on each page.
    </li>
  </ul>
</blockquote>

<h2>CSS is powerful</h2>
<blockquote>
  <h4>Look at this horrible skeleton</h4>
  <p>Let's look at any website of your choice and remove the stylesheets to see what its plain HTML would look like.</p>
</blockquote>

<h2>CSS Rules Are Made of a Selector and Attributes</h2>
<blockquote>
  <p>The <strong>selector</strong> tells the browser what elements to add that style to. On this page we'll only use existing tags, like <code>&lt;h1&gt;</code> and <code>&lt;p&gt;</code>, as our selectors.</p>

  <p>The <strong>attributes</strong> tell the browser how to style the elements you selected. The first part, <code>padding:</code> is a <strong>property</strong>, and the part after the colon <code>20px</code> is the <strong>value</strong>. The line is finished with a semicolon.</p>

  <pre><code>h1 {
  padding: 20px;
}</code></pre>
</blockquote>

<h3>When should I use a class, and when should I use an ID?</h3>
<blockquote>
  <h4>Classes</h4>
  <p>
    A <strong>class</strong> attribute should be used to group elements that <em>could</em> exist
    more than once on a given page. For example, you might give certain
    paragraphs a class of <code>"jumbotron"</code> and use that class to highlight them.
    Even if you only have one paragraph that's jumbotron now, you might
    want to add more later.
  </p>

  <p>
    A class attribute will look like <code>class="jumbotron"</code> in the HTML and <code>.jumbotron</code> in the CSS. Don't mix up where the dot goes!
  </p>

  <h4>IDs</h4>

  <p>
    An <strong>id</strong> is a unique label. Use it to identify things you'd only have one
    of. For example, if you ran a news website, you would only have one element
    on a page that would serve as a masthead, and you could give it an id
    like <code>id="handsome-header"</code>
  </p>

  <p>An id attribute will look like <code>id="handsome-header"</code> in the HTML, and <code>#handsome-header</code> in the CSS.</p>

  <p>Within these guidelines, when you use classes and IDs is a matter of style / taste.</p>
</blockquote>

<h3>Style the comments count column</h3>
<blockquote>
  <p>Align in the middle the comments count from the projects index.</p>
  <h3>Step 1</h3>
  <p>Give the table cell <code>td</code> a class <code>text-center</code></p>
  <h3>Step 2</h3>
  <p>Create a rule to align text to center</p>
  <pre><code>.text-center {
  text-align: center;
}</code></pre>
</blockquote>

app/views/steps/dom_manipulation.html.erb
<h1 class="page-header">DOM Manipulation</h1>
<blockquote>
  <p>
    According to W3C, JavaScript is the most popular programming language in the world. It is the language for HTML, for the Web, for computers, servers, laptops, tablets, smart phones, and more.
  </p>
  <p>In HTML, JavaScript can only be used to manipulate HTML elements.</p>
  <p>The HTML DOM model is constructed as a tree of Objects:</p>
  <p><%= image_tag 'pic_htmltree.gif', alt: '' %></p>
  <p>JavaScript can:</p>
  <ul>
    <li>change all the HTML elements in the page</li>
    <li>change all the HTML attributes in the page</li>
    <li>change all the CSS styles in the page</li>
    <li>remove existing HTML elements and attributes</li>
    <li>add new HTML elements and attributes</li>
    <li>react to all existing HTML events in the page</li>
    <li>create new HTML events in the page</li>
  </ul>
</blockquote>

<h3><code>window</code></h3>
<blockquote>
  <p>The window object represents an open window in a browser.</p>
  <p><a href="http://www.w3schools.com/jsref/obj_window.asp">W3C Javascript Window</a> document has a list of properties and functions you can call on the <code>window</code> object</p>
  <pre><code>window.pageYOffset
window.prompt('What is your favorite color?');
window.alert('Hey you!');</code></pre>
</blockquote>

<h3><code>document</code></h3>
<blockquote>
  <p>
    When a web page is loaded, the browser creates a Document Object Model of the page.
  </p>
  <p>The document object is the root node of the HTML document and the "owner" of all other nodes:
(element nodes, text nodes, attribute nodes, and comment nodes).</p>
<pre><code>document.body
document.domain
document.scripts
document.links
document.images[0].attributes['src'].value</code></pre>
</blockquote>

<h3><code>element</code></h3>
<blockquote>
  <p>The <a href="http://www.w3schools.com/jsref/dom_obj_all.asp">Element</a> represents an HTML element.</p>
  <pre><code>document.firstElementChild
document.firstElementChild.attributes
document.getElementsByClassName('navbar')
document.getElementsByClassName('navbar')[0].getAttribute('class')</code></pre>
</blockquote>

<h3><code>node</code></h3>
<blockquote>
  <p>With the HTML DOM, you can navigate the node tree using node relationships (parent, child, sibling).</p>
  <ul>
    <li>The entire document is a document node</li>
    <li>Every HTML element is an element node</li>
    <li>The text inside HTML elements are text nodes</li>
    <li>Every HTML attribute is an attribute node</li>
    <li>All comments are comment nodes</li>
  </ul>
  <p><%= image_tag 'nodes.png', alt: '' %></p>
</blockquote>

<h3><code>function</code></h3>
<blockquote>
  <pre><code>function replaceName() {
  var myNewName = window.prompt('Pick a new name!');
  document.getElementById('user-name').innerHTML = myNewName;
}

document.onclick = replaceName;</code></pre>
</blockquote>

app/views/steps/front_end_in_rails.html.erb
<h1 class="page-header">Front End in Rails</h1>

<h3>Assets folder</h3>
<blockquote>
  <p>
    In development, all your stylesheets and javascript files can be found in your assets folder under their respective name. Other folders may include images, fonts, svg, flash, etc.
  </p>
  <p>
    In production, your assets are optimized through the <code>Assets Pipeline</code> and are stored in your <code>public</code> folder.
  </p>
</blockquote>

<h3>Assets Pipeline</h3>
<blockquote>
  <p>
    The Rails <a href="http://guides.rubyonrails.org/asset_pipeline.html">Asset Pipeline</a> provides a framework to concatenate and minify or compress JavaScript and CSS assets. It also adds the ability to write these assets in other languages and pre-processors such as CoffeeScript, Sass and ERB.
  </p>

  <h4>Benefits:</h4>
  <ul>
    <li><h5>Concatenate</h5></li>
    <li><h5>Minify</h5></li>
    <li><h5>Compress</h5></li>
    <li><h5>Fingerprint</h5></li>
    <li><h5>Pre-processor compiling</h5></li>
  </ul>
</blockquote>

<h3>Manifest Files</h3>
<blockquote>
  <p>
    Sprockets uses <a href="http://guides.rubyonrails.org/asset_pipeline.html#manifest-files-and-directives">manifest files</a> to determine which assets to include and serve. These manifest files contain directives - instructions that tell Sprockets which files to require in order to build a single CSS or JavaScript file.
  </p>

  <pre><code># application.js

//= require jquery
//= require jquery_ujs
//= require jquery.turbolinks
//= require_tree .
//= require turbolinks</code></pre>

  <pre><code># application.css.scss
@import "bourbon";
@import "neat";

// Vendors
@import "select2";
@import "shadowbox";
@import "mousetrap";
@import "vendor/*";

// SMACCS
@import "settings/*";
@import "mixins/*";
@import "layout/*";
@import "components/*";
@import "modules/*";
@import "overrides/*";</code></pre>
</blockquote>

app/views/steps/getting_started.html.erb
<h1 class="page-header">Getting Started</h1>
<blockquote>
  <h3>Let's start fresh!</h3>
  <p>
    We need to make sure we all work from the same code base.
  </p>
</blockquote>

<h3>Step 1</h3>
<blockquote>
  <p>Whether you did not complete the tutorial from Rails Intermediate or if you would like to start fresh, clone the following repository:</p>

  <pre><code>git clone https://github.com/mathieugagne/milo-app.git</code></pre>

</blockquote>

<h3>Step 2</h3>
<blockquote>
  <div class="console">
    <span>Type this in the terminal:</span><pre>cd milo-app</pre>
  </div>
  <div class="message">
    <p>'cd' stands for change directory.</p>
  </div>
  <div class="message">
    <p>'cd milo-app' makes milo our current directory.</p>
  </div>
</blockquote>

<h3>Step 3</h3>
<blockquote>
  <div class="message">
    <p>Open the milo-app folder as a project in your text editor.</p>

    <p>In <strong>Sublime Text 2</strong>, you can use the <code>Project &gt; Add Folder to Project...</code> menu option:</p>

    <p><%= image_tag "sublime_add_folder_to_project.png", alt: '' %></p>
  </div>
</blockquote>

app/views/steps/html_document_structure.html.erb
<h1 class="page-header">HTML Document Structure</h1>

<h3>The HTML tag and Doctype</h3>
<blockquote>

  <p>
    The line <code>&lt;!DOCTYPE html&gt;</code> is called the doctype, and it tells the browser which flavor of HTML you're using. <code>&lt;!DOCTYPE html&gt;</code> tells your browser you're using HTML5, the latest version of HTML.
  </p>

  <p>
    (You may see older doctypes out there that are longer and a lot more complicated, from when people
    used various HTML and XHTML versions, but those are annoying, and you can usually just
    use this short version for new websites.)
  </p>

  <p>The <code>&lt;html&gt;</code> encloses all the rest of your page, and states unequivocally, "Here is my HTML!!!"</p>
</blockquote>

<h3>Pages, Like People, Have a Head and a Body</h3>
<blockquote>
  <pre><code>&lt;!DOCTYPE html&gt;
&lt;html&gt;
  &lt;head&gt;Invisible, Important Stuff&lt;/head&gt;
  &lt;body&gt;Actual Visible Content&lt;/body&gt;
&lt;/html&gt;</code></pre>

  <h3>The Head</h3>

  <p>The head contains information <em>about</em> the document, including:</p>

  <ul>
    <li>what language or character set you're using</li>
    <li>what the page title should be</li>
    <li>what CSS and JavaScript files to include (and where they are)</li>
  </ul>

  <p>
    Information in the <code>&lt;head&gt;</code> section is <strong>not</strong> displayed.
  </p>

  <p>
    It can also contain metadata tags that can tell a search engine or another
    program more about the file, like who wrote it or what keywords are relevant.
  </p>

  <h3>The Body</h3>

  <p>
    The Body contains the actual content of your file, the things you'll want your users
    to be able to see, read, or interact with!
  </p>

  <h3>Most used tags</h3>
  <table class='table'>
    <thead>
      <tr>
        <th>Tag</th>
        <th>Purpose</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>a</td>
        <td>A link (the 'a' stands for Anchor)</td>
      </tr>
      <tr>
        <td>h1-h6</td>
        <td>Various headers, h1 is the most important, h6 the least.</td>
      </tr>
      <tr>
        <td>ul</td>
        <td>Start a bulleted list (an 'unordered list')</td>
      </tr>
      <tr>
        <td>ol</td>
        <td>Start a numbered list (an 'ordered list')</td>
      </tr>
      <tr>
        <td>li</td>
        <td>A single thing within a list (a 'list item')</td>
      </tr>
      <tr>
        <td>table, tr, td</td>
        <td>You can make tables (like this one) with table rows and data cells</td>
      </tr>
      <tr>
        <td>form</td>
        <td>A form that can collect data from user input</td>
      </tr>
      <tr>
        <td>input</td>
        <td>A text input, a button, or a checkbox in a form</td>
      </tr>
      <tr>
        <td>div</td>
        <td>A section marker that doesn't do anything specific to the contents itself, but does make a new line after. (More on this later.)</td>
      </tr>
      <tr>
        <td>span</td>
        <td>Another section marker that doesn't do anything to its contents, but is inline - it does not make a new line after.</td>
      </tr>
    </tbody>
  </table>
</blockquote>